[package]
name = "wallet-types"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialization = { path = "../../serialization" }
common = { path = "../../common/" }

thiserror.workspace = true
parity-scale-codec.workspace = true
