[package]
name = "wallet-types"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common/" }
crypto = { path = "../../crypto/" }
serialization = { path = "../../serialization" }
storage = { path = '../../storage', features = ['inmemory'] }

bip39 = { version = "2.0", default-features = false, features = ["std", "zeroize"] }
zeroize = "1.5"
thiserror.workspace = true
parity-scale-codec.workspace = true

[dev-dependencies]
test-utils = { path = "../../test-utils" }

rstest = "0.17"
