[package]
name = "storage-backend-test-suite"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"

[dependencies]
storage-core = { path = "../core" }
utils = { path = "../../utils" }
logging = { path = "../../logging" }

libtest-mimic = "0.6"
proptest = "1.0"
