[package]
name = "storage-backend-test-suite"
license = "MIT"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
storage-core = { path = "../core" }
utils = { path = "../../utils" }
logging = { path = "../../logging" }

libtest-mimic = "0.6"
proptest = "1.0"
