version: "3.8"

services:
  node01:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node01

    volumes:
      - data01:$DATA_DIR_IN_CONTAINER
    ports:
      - '40001:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

  node02:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node02

    volumes:
      - data02:$DATA_DIR_IN_CONTAINER
    ports:
      - '40002:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

  node03:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node03

    volumes:
      - data03:$DATA_DIR_IN_CONTAINER
    ports:
      - '40003:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

  node04:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node04

    volumes:
      - data04:$DATA_DIR_IN_CONTAINER
    ports:
      - '40004:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

  node05:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node05

    volumes:
      - data05:$DATA_DIR_IN_CONTAINER
    ports:
      - '40005:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

  node06:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node06

    volumes:
      - data06:$DATA_DIR_IN_CONTAINER
    ports:
      - '40006:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

  node07:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node07

    volumes:
      - data07:$DATA_DIR_IN_CONTAINER
    ports:
      - '40007:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

  node08:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node08

    volumes:
      - data08:$DATA_DIR_IN_CONTAINER
    ports:
      - '40008:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

  node09:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node09

    volumes:
      - data09:$DATA_DIR_IN_CONTAINER
    ports:
      - '40009:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

  node10:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node10

    volumes:
      - data10:$DATA_DIR_IN_CONTAINER
    ports:
      - '40010:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

  node11:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node11

    volumes:
      - data11:$DATA_DIR_IN_CONTAINER
    ports:
      - '40011:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

  node12:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node12

    volumes:
      - data12:$DATA_DIR_IN_CONTAINER
    ports:
      - '40012:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

  node13:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node13

    volumes:
      - data13:$DATA_DIR_IN_CONTAINER
    ports:
      - '40013:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

  node14:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node14

    volumes:
      - data14:$DATA_DIR_IN_CONTAINER
    ports:
      - '40014:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

  node15:
    build:
      context: ../..
      dockerfile: build-tools/p2p-v2-test/Dockerfile
    container_name: $BASE_NAME-node15

    volumes:
      - data15:$DATA_DIR_IN_CONTAINER
    ports:
      - '40015:$RPC_PORT'
    command: bash -c "$NODE_DAEMON_CMD"
    environment:
      - RUST_LOG

volumes:
  data01:
  data02:
  data03:
  data04:
  data05:
  data06:
  data07:
  data08:
  data09:
  data10:
  data11:
  data12:
  data13:
  data14:
  data15:
