[package]
name = "tx-verifier"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = '../../common'}
consensus = {path = '../../consensus'}
chainstate-storage = {path = '../storage'}
chainstate-types = {path = '../types'}
crypto = {path = '../../crypto'}
pos_accounting = {path = '../../pos_accounting'}
utils = {path = '../../utils'}
utxo = {path = '../../utxo'}

thiserror.workspace = true
fallible-iterator = "0.2.0"
replace_with = "0.1"

[dev-dependencies]
test-utils = { path = "../../test-utils" }

rstest = "0.16"
mockall = "0.11"
