[package]
name = "serialization-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec-derive = "2.3.1"
syn = { version = "1.0.8", features = ["full", "visit"] }
quote = "1.0.2"
proc-macro2 = "1.0.6"
proc-macro-crate = "1.0.0"

[dependencies.codec]
default-features = false
features = ["derive", "chain-error"]
package = 'parity-scale-codec'
version = "2.3.1"