# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"

stages:  
  - fmt        # List of stages for jobs, and their order of execution
  - build
  - test
  - sgh
  - fn

fmt-job:
  stage: fmt
  script:
    cargo fmt --all -- --check

build-job:
  stage: build
  script:
    cargo build --release --locked

test-job:
  stage: test
  script:
    cargo test --release --workspace

sighash-job:
  stage: sgh
  script:
    cargo test --release -p common mixed_sighash_types -- --ignored

fntest-job:
  stage: fn
  script:
    cargo test --release -p mintlayer-test --test functional -- --ignored
