[bans]
multiple-versions = "deny" #catch mutliple versions of a crate
deny = []
skip = []

[licenses]
unlicensed = "deny"
confidence-threshold = 0.92
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
] #deny a license not in this set of licenses
