[package]
name = "p2p-backend-test-suite"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"

[dependencies]
common = { path = "../../common" }
p2p = { path = "../../p2p", features = ["testing_utils"] }
p2p-test-utils = { path = "../p2p-test-utils" }
logging = { path = "../../logging" }
serialization = { path = "../../serialization" }
chainstate = { path = "../../chainstate/" }
subsystem = { path = "../../subsystem/" }

tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync", "time"] }
futures.workspace = true
libtest-mimic = "0.6"
