[package]
name = "rpc"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
jsonrpsee = { version = "0.10.1", features = ["full"] }

[dev-dependencies]
tokio = "1.17.0"
