[package]
name = "rpc"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto = { path = "../crypto/" }
logging = { path = "../logging" }
subsystem = { path = "../subsystem" }
utils = { path = "../utils/" }

anyhow = "1.0"
async-trait.workspace = true
base64 = "0.21"
http = "0.2"
hyper = "0.14"
jsonrpsee = { workspace = true, features = ["full"] }
thiserror.workspace = true
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.3", features = ["auth"] }

[dev-dependencies]
test-utils = { path = "../test-utils" }

rstest.workspace = true
tokio.workspace = true
