[package]
name = "rpc"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Local dependencies
subsystem = { path = "../subsystem" }
logging = { path = "../logging" }
utils = { path = "../utils/" }

# External dependencies
anyhow = "1.0"
async-trait.workspace = true
jsonrpsee = { workspace = true, features = ["full"] }

[dev-dependencies]
tokio.workspace = true
