[package]
name = "wallet"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = '../common'}
crypto = { path = "../crypto/" }
logging = { path = "../logging" }
serialization = { path = "../serialization" }
storage = { path = '../storage', features = ['inmemory'] }
utxo = { path = '../utxo' }
wallet-storage = {path = './storage'}
wallet-types = {path = './types'}

bip39 = { version = "1.0", default-features = false} #TODO use `features = ["std"]`
zeroize = "1.5.7"
thiserror.workspace = true

[dev-dependencies]
test-utils = { path = "../test-utils" }

tempfile = "3.3"