[package]
name = "accounting"
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = '../common'}
crypto = {path = '../crypto'}
chainstate-types = {path = '../chainstate-types'}

thiserror = "1.0"
