[package]
name = "node-comm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chainstate = { path = "../../chainstate/" }
common = { path = '../../common' }
serialization = {path = "../../serialization"}
subsystem = { path = "../../subsystem/" }

async-trait.workspace = true
thiserror.workspace = true

jsonrpsee = { version = "0.16" }
serde_json = "1.0"
http = "0.2"
base64 = "0.21"

[dev-dependencies]
chainstate-storage = { path = "../../chainstate/storage" }
rpc = { path = "../../rpc/" }

tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "sync"] }
