[package]
name = "node-comm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chainstate = { path = "../../chainstate" }
common = { path = "../../common" }
node-lib = { path = "../../node-lib" }
p2p = { path = "../../p2p" }
rpc = { path = "../../rpc" }
serialization = { path = "../../serialization" }
subsystem = { path = "../../subsystem" }
tower = "0.4"

async-trait.workspace = true
jsonrpsee.workspace = true
thiserror.workspace = true

serde_json = "1.0"
http = "0.2"
base64 = "0.21"

[dev-dependencies]
chainstate-storage = { path = "../../chainstate/storage" }

tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "sync"] }
