[package]
name = "node-comm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blockprod = { path = "../../blockprod" }
chainstate = { path = "../../chainstate" }
common = { path = "../../common" }
consensus = { path = "../../consensus" }
logging = { path = "../../logging" }
mempool = { path = "../../mempool" }
node-lib = { path = "../../node-lib" }
p2p = { path = "../../p2p" }
rpc = { path = "../../rpc" }
serialization = { path = "../../serialization" }
subsystem = { path = "../../subsystem" }

async-trait.workspace = true
base64.workspace = true
jsonrpsee.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tower.workspace = true

[dev-dependencies]
chainstate-storage = { path = "../../chainstate/storage" }

tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "sync"] }
