[package]
name = "p2p"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []
testing_utils = ["dep:test-utils", "tokio/test-util"]

[dependencies]
common = { path = "../common/" }
crypto = { path = "../crypto/" }
chainstate = { path = "../chainstate/" }
logging = { path = "../logging/" }
mempool = { path = "../mempool/" }
rpc = { path = "../rpc/" }
serialization = { path = "../serialization/" }
subsystem = { path = "../subsystem/" }
utils = { path = "../utils/" }
storage = { path = "../storage" }
test-utils = { path = "../test-utils", optional = true }

async-trait.workspace = true
bytes = "1.1"
futures.workspace = true
itertools.workspace = true
parity-scale-codec.workspace = true
sscanf = "0.4"
thiserror.workspace = true
void = "1.0"
tap = "1.0"
once_cell.workspace = true
jsonrpsee = { workspace = true, features = ["macros"] }
tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync", "time"] }
tokio-util = {version = "0.7", default-features = false, features = ["codec"] }
snowstorm = "0.4.0"
serde.workspace = true
socket2 = { version = "0.5", features = ["all"] }
tokio-socks = { version = "0.5.1" }
hex.workspace = true

[dev-dependencies]
chainstate-test-framework = { path = "../chainstate/test-framework" }
chainstate-storage = { path = "../chainstate/storage" }
crypto = { path = "../crypto/" }
p2p-test-utils = { path = "p2p-test-utils" }
p2p-backend-test-suite = { path = "backend-test-suite" }
test-utils = { path = "../test-utils" }
consensus = { path = "../consensus" }

portpicker = "0.1"
rstest = "0.16"

[[test]]
name = "backend_tcp"
harness = false

[[test]]
name = "backend_channels"
harness = false

[[test]]
name = "backend_noise"
harness = false
