[package]
name = "p2p"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
common = { path = "../common/" }
crypto = { path = "../crypto/" }
chainstate = { path = "../chainstate/" }
logging = { path = "../logging/" }
mempool = { path = "../mempool/" }
rpc = { path = "../rpc/" }
serialization = { path = "../serialization/" }
subsystem = { path = "../subsystem/" }
utils = { path = "../utils/" }

async-trait = "0.1"
bytes = "1.1"
futures = "0.3"
itertools = "0.10"
parity-scale-codec = "3.1"
sscanf = "0.3"
thiserror = "1.0"
void = "1.0"
tap = "1.0"
once_cell = "1.13"
jsonrpsee = { version = "0.15", features = ["macros"]}
libp2p = { version = "0.46", default-features = false, features = ["gossipsub", "identify", "mdns", "mplex", "noise", "ping", "request-response", "tcp-tokio"] }
tokio = { version = "1", default-features = false, features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync", "time"] }
tokio-util = {version = "0.7", default-features = false, features = ["codec"] }

[dev-dependencies]
chainstate-storage = { path = "../chainstate/storage" }
crypto = { path = "../crypto/" }
p2p-test-utils = { path = "p2p-test-utils" }

portpicker = "0.1"

