[package]
name = "p2p"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
async-trait = "0.1.51"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '2.0.0'
