[package]
name = "p2p"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
default = []
testing_utils = []

[dependencies]
common = { path = "../common/" }
crypto = { path = "../crypto/" }
chainstate = { path = "../chainstate/" }
logging = { path = "../logging/" }
mempool = { path = "../mempool/" }
rpc = { path = "../rpc/" }
serialization = { path = "../serialization/" }
subsystem = { path = "../subsystem/" }
utils = { path = "../utils/" }

async-trait = "0.1"
bytes = "1.1"
futures = "0.3"
itertools = "0.10"
parity-scale-codec = "3.1"
sscanf = "0.4"
thiserror = "1.0"
void = "1.0"
tap = "1.0"
once_cell = "1.13"
jsonrpsee = { version = "0.16", features = ["macros"]}
tokio = { version = "1", default-features = false, features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync", "time"] }
tokio-util = {version = "0.7", default-features = false, features = ["codec"] }
snowstorm = "0.4.0"
serde = "1.0"
socket2 = { version = "0.4.0", features = ["all"] }

[dev-dependencies]
chainstate-storage = { path = "../chainstate/storage" }
crypto = { path = "../crypto/" }
p2p-test-utils = { path = "p2p-test-utils" }
p2p-backend-test-suite = { path = "backend-test-suite" }

portpicker = "0.1"

[[test]]
name = "backend_mock_tcp"
harness = false

[[test]]
name = "backend_mock_channels"
harness = false

[[test]]
name = "backend_mock_noise"
harness = false
