[package]
name = "p2p"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
async-trait = "0.1.51"
futures = "0.3.15"
futures-timer = "3.0.2"
itertools = "0.10.3"
lazy_static = "1.4.0"
parity-scale-codec = "3.1.2"
sscanf = "0.2.1"
thiserror = "1.0"
void = "1.0.2"

# local dependencies
common = { path = "../common/" }
chainstate = { path = "../chainstate/" }
crypto = { path = "../crypto/" }
logging = { path = "../logging/" }
rpc = { path = "../rpc/" }
serialization = { path = "../serialization/" }
subsystem = { path = "../subsystem/" }
utils = { path = "../utils/" }

[dependencies.jsonrpsee]
version = "0.14.0"
features = ["macros"]

[dependencies.libp2p]
version = "0.45.1"
default-features = false
features = ["gossipsub", "identify", "mdns", "mplex", "noise", "ping", "request-response", "tcp-async-io"]

[dependencies.tokio]
version = "1"
default-features = false
features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync", "time"]

[dev-dependencies]
portpicker = "0.1.1"
blockchain-storage = { path = "../blockchain_storage" }

[dev-dependencies.test-utils]
version = "0.1.0"
path = "test-utils"
