[package]
name = "storage-inmemory"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]

# Local dependencies
storage-core = { path = "../core" }

[dev-dependencies]
utils = { path = "../../utils" }
