[package]
name = "blockprod"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chainstate = { path = "../chainstate/" }
chainstate-storage = { path = "../chainstate/storage/" }
common = { path = "../common/" }
mempool = { path = "../mempool/" }
subsystem = { path = "../subsystem/" }
logging = {path = '../logging'}
utils = {path = '../utils'}
rpc = { path = "../rpc/" }

thiserror.workspace = true
tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync", "time"] }
futures.workspace = true
void = "1.0"
crossbeam-channel = "0.5"
jsonrpsee = { workspace = true, features = ["macros"] }
async-trait.workspace = true
