[package]
name = "api-server-stack-test-suite"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dev-dependencies]
api-server-common = { path = "../api-server-common" }
chainstate-test-framework = { path = '../../chainstate/test-framework' }
common = { path = "../../common" }
crypto = { path = "../../crypto" }
api-blockchain-scanner-lib = { path = "../scanner-lib" }
utils = { path = "../../utils" }
api-web-server = { path = "../web-server" }

async-trait.workspace = true
axum.workspace = true
hex.workspace = true
libtest-mimic.workspace = true
reqwest = "0.11"
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
rstest.workspace = true
test-utils = {path = '../../test-utils'}
