[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto = {path = '../crypto'}
rand_chacha = "0.3.1"
