[package]
name = "test-utils"
license = "MIT"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = '../common'}
crypto = {path = '../crypto'}
serialization = { path = '../serialization' }

rand_chacha = "0.3.1"
