[package]
name = "serialization"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serialization-core = { path = 'core' }
serialization-tagged = { path = 'tagged' }

hex.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
