[package]
name = "serialization"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"

[dependencies]
serialization-core = { path = 'core' }
serialization-tagged = { path = 'tagged' }
