[package]
name = "storage-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"

[dependencies]

# Local dependencies
utils = { path = '../../utils' }
logging = { path = '../../logging' }

# External dependencies
thiserror.workspace = true
itertools.workspace = true
