[package]
name = "subsystem"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"

[features]
default = [ "time" ]
time = [ "tokio/time" ]

[dependencies]
# Local dependencies
logging = { path = "../logging" }

# External dependencies
async-trait.workspace = true
cfg-if = "1.0"
thiserror.workspace = true
futures = { workspace = true, default-features = false, features = ["alloc"]}
tokio = { workspace = true, default-features = false, features = ["macros", "rt", "rt-multi-thread", "signal", "sync"]}

[dev-dependencies]
testing_logger = "0.1"

utils = { path = "../utils" }
