[package]
name = "storage-sqlite"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
logging = { path = '../../logging' }
storage-core = { path = '../core' }
utils = { path = '../../utils' }

rusqlite = { version = "0.29", features = ["bundled"] }

[dev-dependencies]
storage-backend-test-suite = { path = "../backend-test-suite" }
test-utils = { path = "../../test-utils" }
utils = { path = '../../utils' }

[[test]]
name = "backend"
harness = false
