[package]
name = "constraints-value-accumulator"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = '../../common'}
crypto = {path = '../../crypto'}
pos_accounting = {path = '../../pos_accounting'}
utils = {path = '../../utils'}
utxo = {path = '../../utxo'}

thiserror.workspace = true

[dev-dependencies]
test-utils = { path = "../../test-utils" }

rstest.workspace = true
