[package]
name = "blockchain-storage"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
storage = { path = '../storage'}
common = { path = '../common' }
mockall = { version = "0.11", optional = true }
parity-scale-codec = { version = "2.3.1", features = ["chain-error"] }

[dev-dependencies]
mockall = "0.11"

[features]
mock = [ 'mockall' ]
