[package]
name = "typename-derive"
license = "MIT"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
itertools.workspace = true
