[package]
name = "storage"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = [ 'inmemory' ]
# Enable the in-memory backend
inmemory = [ 'storage-inmemory' ]

[dependencies]
serialization = { path = "../serialization" }
storage-core = { path = "core" }
storage-inmemory = { path = "inmemory", optional = true }
utils = { path = "../utils" }

[dev-dependencies]
storage-inmemory = { path = "inmemory" }
