[package]
name = "storage"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
common = { path = "../common"}
serialization = { path = "../serialization"}
logging = { path = '../logging' }
thiserror = "1.0"
