[package]
name = "serialization-tagged"
license = "MIT"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serialization-core = { path = '../core' }
serialization-tagged-derive = { path = 'derive' }

static_assertions.workspace = true

[dev-dependencies]
serialization = { path = '..' }

parity-scale-codec = { workspace = true, features = ["derive", "chain-error"] }
proptest = "1.0"
