[package]
name = "serialization-tagged"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serialization-core = { path = '../core' }
serialization-tagged-derive = { path = 'derive' }

static_assertions.workspace = true

[dev-dependencies]
serialization = { path = '..' }

parity-scale-codec = { workspace = true, features = ["derive", "chain-error"] }
proptest = "1.0"
