[package]
name = "chainstate-test-suite"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
accounting = {path = '../../accounting'}
chainstate-test-framework = { path = '../test-framework' }
chainstate = { path = '../' }
chainstate-storage = { path = '../storage' }
chainstate-types = { path = '../types' }
common = { path = '../../common' }
consensus = { path = '../../consensus' }
crypto = { path = '../../crypto' }
logging = { path = '../../logging' }
pos_accounting = {path = '../../pos_accounting'}
serialization = { path = '../../serialization' }
test-utils = {path = '../../test-utils'}
tx-verifier = { path = '../tx-verifier' }
utils = { path = '../../utils' }
utxo = { path = '../../utxo' }

hex.workspace = true
itertools.workspace = true

[dev-dependencies]
rstest = "0.16"
expect-test = "1.3"
