[package]
name = "chainstate"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
chainstate-storage = {path = './storage', features = ["mock"]}
chainstate-types = {path = './types'}
tx-verifier = {path = './tx-verifier'}
common = {path = '../common'}
crypto = {path = '../crypto'}
logging = {path = '../logging'}
pos_accounting = {path = '../pos_accounting'}
rpc = {path = '../rpc'}
serialization = {path = "../serialization"}
subsystem = {path = '../subsystem'}
utxo = {path = '../utxo'}
utils = {path = '../utils'}
consensus = {path = "../consensus"}
oneshot = "0.1"

async-trait.workspace = true
hex.workspace = true
itertools.workspace = true
jsonrpsee = { workspace = true, features = ["macros"] }
thiserror.workspace = true
mockall = "0.11"
serde_json = "1.0"
serde = { workspace = true, features = ["derive"] }
static_assertions.workspace = true
tokio.workspace = true

[dev-dependencies]
test-utils = { path = "../test-utils" }

rstest.workspace = true
