[package]
edition = "2021"
license = "MIT"
name = "chainstate"
version = "0.1.0"

[dependencies]
chainstate-storage = {path = './storage'}
chainstate-types = {path = './types'}
tx-verifier = {path = './tx-verifier'}
common = {path = '../common'}
crypto = {path = '../crypto'}
logging = {path = '../logging'}
pos_accounting = {path = '../pos_accounting'}
rpc = {path = '../rpc'}
serialization = {path = "../serialization"}
subsystem = {path = '../subsystem'}
utxo = {path = '../utxo'}
utils = {path = '../utils'}
consensus = {path = "../consensus"}

async-trait.workspace = true
hex.workspace = true
itertools.workspace = true
jsonrpsee = { workspace = true, features = ["macros"] }
thiserror.workspace = true
generic-array = "0.14"
mockall = "0.11"
rstest = "0.16"
serde_json = "1.0"
static_assertions.workspace = true
tokio.workspace = true

[dev-dependencies]
rstest = "0.16"
test-utils = { path = "../test-utils" }
