[package]
name = "p2p-test-utils"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
chainstate-storage = { path = "../../chainstate/storage" }
chainstate = { path = "../../chainstate/" }
common = { path = "../../common/" }
crypto = { path = "../../crypto/" }
mempool = { path = "../../mempool/" }
p2p = { path = "../" }
subsystem = { path = "../../subsystem/" }

portpicker = "0.1"
tokio = { version = "1", default-features = false, features = ["io-util", "macros", "net", "rt", "sync"] }
libp2p = { version = "0.46", default-features = false, features = ["gossipsub", "identify", "mdns", "mplex", "noise", "ping", "tcp-async-io"] }
