[package]
name = "p2p-test-utils"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"

[dependencies]
chainstate-storage = { path = "../../chainstate/storage" }
chainstate = { path = "../../chainstate/" }
common = { path = "../../common/" }
crypto = { path = "../../crypto/" }
mempool = { path = "../../mempool/" }
subsystem = { path = "../../subsystem/" }

portpicker = "0.1"
tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "sync"] }
