[package]
name = "script"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
crypto = { path = '../crypto' }
serialization = { path = "../serialization" }
typename = { path = "../utils/typename" }
utils = { path = '../utils' }

parity-scale-codec.workspace = true
thiserror.workspace = true

[dev-dependencies]
logging = { path = '../logging' }

flate2.workspace = true
hex.workspace = true
hex-literal.workspace = true
proptest.workspace = true

[features]
default = ['testcontext']
testcontext = []
