[package]
name = "script"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
crypto = { path = '../crypto' }
serialization = { path = "../serialization" }
utils = { path = '../utils' }

parity-scale-codec = "3.1.2"
thiserror = "1.0"

[dev-dependencies]
flate2 = "1.0.22"
hex = "0.4.3"
hex-literal = "0.3.1"
proptest = "1.0.0"
logging = { path = '../logging' }

[features]
default = ['testcontext']
testcontext = []
