[package]
name = "script"
version = "0.1.0"
edition = "2018"

[dependencies]
displaydoc = { default-features = false, version = "0.2" }
crypto = { path = '../crypto' }

[dev-dependencies]
# serde = '1.0.119'
hex-literal = "0.3.1"
proptest = "1.0.0"

[features]
default = ['testcontext']
testcontext = []
