[package]
name = "script"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
crypto = { path = '../crypto' }
serialization = { path = "../serialization" }
utils = { path = '../utils' }
typename = { path = "../utils/typename" }

parity-scale-codec = "3.1"
thiserror = "1.0"

[dev-dependencies]
flate2 = "1.0"
hex = "0.4"
hex-literal = "0.3"
proptest = "1.0"
logging = { path = '../logging' }

[features]
default = ['testcontext']
testcontext = []
