[package]
name = "script"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
crypto = { path = '../crypto' }
serialization = { path = "../serialization" }
utils = { path = '../utils' }
typename = { path = "../utils/typename" }

parity-scale-codec.workspace = true
thiserror.workspace = true

[dev-dependencies]
logging = { path = '../logging' }

flate2 = "1.0"
hex.workspace = true
hex-literal = "0.4"
proptest = "1.0"

[features]
default = ['testcontext']
testcontext = []
