[package]
name = "script"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
displaydoc = { default-features = false, version = "0.2" }
crypto = { path = '../crypto' }

parity-scale-codec = {version = "2.3.1", features = ["derive", "chain-error"]}
parity-scale-codec-derive = "2.3.1"

[dev-dependencies]
flate2 = "1.0.22"
hex = "0.4.3"
hex-literal = "0.3.1"
proptest = "1.0.0"

[features]
default = ['testcontext']
testcontext = []
