[package]
name = "common"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
script = { path = '../script'}
crypto = { path = '../crypto'}
serialization = { path = "../serialization" }
logging = { path = "../logging/" }

anyhow = "1.0.51"
bech32 = "0.8.1"
displaydoc = { default-features = false, version = "0.2" }
generic-array = "0.14.4"
hex-literal = "0.3.4"
lazy_static = "1.4.0"
merkletree = "0.21.0"
parity-scale-codec = "3.1.2"
rand = "0.8.4"
sscanf = "0.2.1"
static_assertions = "1.1.0"
thiserror = "1.0.30"

# for fixed_hash
arbitrary = "1.1.0"
byteorder = "1.4.3"
rustc-hex = "2.1.0"

[dev-dependencies]
bitcoin-bech32 = "0.12.1"
hex = "0.4.3"
expect-test = "1.2.2"

[target.'cfg(loom)'.dependencies]
loom = "0.5"
