[package]
name = "common"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixed-hash = { version = "0.7.0", default-features = true, features = ["std"] }
script = { path = '../script'}
crypto = { path = '../crypto'}
hex-literal = "0.3.4"
