[package]
name = "api-server-common"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = '../../common' }
crypto = { path = '../../crypto/' }
logging = {path = '../../logging'}
serialization = { path = "../../serialization" }

async-trait.workspace = true
parity-scale-codec.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-postgres = "0.7"
ouroboros = "0.18"
bb8-postgres = "0.8"

[dev-dependencies]
chainstate-test-framework = { path = '../../chainstate/test-framework' }
test-utils = {path = '../../test-utils'}

rstest.workspace = true
