[package]
name = "utils"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
logging = {path = '../logging'}
crypto = { path = "../crypto/" }

atomic-traits = "0.3"
num-traits = "0.2"
slave-pool = "0.2"
probabilistic-collections = "0.7"

[dev-dependencies]
test-utils = { path = "../test-utils" }

static_assertions.workspace = true
criterion = "0.3"
rstest.workspace = true

[target.'cfg(loom)'.dependencies]
loom = "0.5"

[[bench]]
name = "benches"
harness = false
