[package]
name = "utils"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"

[dependencies]
logging = {path = '../logging'}

atomic-traits = "0.3"
num-traits = "0.2"
slave-pool = "0.2"

[dev-dependencies]
static_assertions.workspace = true

[target.'cfg(loom)'.dependencies]
loom = "0.5"
