[package]
name = "utils"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
atomic-traits = "0.3"
num-traits = "0.2"
slave-pool = "0.2"

[target.'cfg(loom)'.dependencies]
loom = "0.5"
