[package]
name = "chainstate-types"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialization = { path = "../../serialization" }
common = { path = "../../common/" }
storage = { path = "../../storage/" }

thiserror.workspace = true
parity-scale-codec.workspace = true
