[package]
name = "chainstate-types"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common/" }
crypto = { path = "../../crypto" }
logging = { path = '../../logging' }
serialization = { path = "../../serialization" }
storage = { path = "../../storage/" }
utils = { path = "../../utils/" }

enum-iterator.workspace = true
num-derive.workspace = true
num-traits.workspace = true
generic-array.workspace = true
parity-scale-codec.workspace = true
thiserror.workspace = true
