[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
portpicker = "0.1.1"
p2p = { path = "../" }
common = { path = "../../common/" }

[dependencies.libp2p]
version = "0.45.1"
default-features = false
features = ["gossipsub", "identify", "mdns", "mplex", "noise", "ping", "tcp-async-io"]

[dependencies.tokio]
version = "1"
default-features = false
features = ["io-util", "macros", "net", "rt", "sync"]
