[package]
name = "consensus"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
chainstate-types = {path = '../chainstate/types'}
common = {path = '../common'}
crypto = {path = '../crypto'}
lazy_static = "1.4"
pos_accounting = {path = '../pos_accounting'}
utils = {path = "../utils"}
utxo = {path = '../utxo'}

thiserror.workspace = true
itertools.workspace = true
num = "0.4"

[dev-dependencies]
rstest.workspace = true
test-utils = {path = '../test-utils'}
