[package]
name = "consensus"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
common = {path = '../common'}
chainstate-types = {path = '../chainstate/types'}
chainstate-storage = {path = '../chainstate/storage'}

thiserror.workspace = true
num = "0.4.0"

[dev-dependencies]
rstest = "0.16"
