[package]
name = "consensus"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
blockchain-storage = { path = '../blockchain_storage'}
common = { path = '../common' }
crypto = { path = '../crypto' }
jsonrpsee = { version = "0.10", features = ["macros"] }
num = "0.4.0"
rand = "0.8.4"
logging = { path = '../logging' }
thiserror = "1.0.30"
proptest = "1.0.0"
serialization = { path = "../serialization" }
replace_with = "0.1.7"
rpc = { path = '../rpc' }
slave-pool = "0.2.3"
subsystem = { path = '../subsystem' }

[dev-dependencies]
static_assertions = "1.1"
