[package]
edition = "2021"
license = "MIT"
name = "consensus"
version = "0.1.0"

[dependencies]
common = {path = '../common'}
chainstate-types = {path = '../chainstate/types'}
chainstate-storage = {path = '../chainstate/storage'}

thiserror.workspace = true
num = "0.4.0"

[dev-dependencies]
rstest = "0.16"
