[package]
name = "utxo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = '../common' }
parity-scale-codec = { version = "2.3.1", features = ["chain-error"] }
rand = "0.8.4"
