[package]
name = "utxo"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = '../common' }
logging = { path = "../logging/" }
serialization = { path = "../serialization" }
chainstate-types = { path = '../chainstate/types' }

parity-scale-codec = { workspace = true, features = ["chain-error"] }
thiserror.workspace = true

[dev-dependencies]
crypto = { path = '../crypto' }
test-utils = {path = '../test-utils'}

itertools.workspace = true
rstest = "0.17"
