[package]
name = "utxo"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = '../common' }
crypto = { path = '../crypto' }
parity-scale-codec = { version = "2.3.1", features = ["chain-error"] }
iter_tools = "0.1.0"
thiserror = "1.0.30"
