[package]
name = "serialization-utils"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec-derive = "2.3.1"
parity-scale-codec = {version = "2.3.1", features = ["derive", "chain-error"]}