[package]
name = "wallet-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wallet-cli-lib = { path = "../wallet-cli-lib" }

clap = { version = "4", features = ["derive"] }
tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "sync"] }
