[package]
name = "wallet-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
logging = { path = "../../logging" }
node-comm = { path = "../wallet-node-client" }
utils = { path = "../../utils" }
wallet = { path = ".." }
wallet-storage = { path = '../storage' }

clap = { version = "4", features = ["derive"] }
dialoguer = { version = "0.10", features = ["history", "completion"] }
directories = "5.0"
thiserror.workspace = true
tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "sync"] }

[dev-dependencies]
