[package]
name = "crypto"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Samer Afach <samer.afach@mintlayer.org>", "Ben Marsh <benjamin.marsh@mintlayer.org>", "Enrico Rubboli <enrico.rubboli@mintlayer.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.10.0"
sha2 = "0.10.0"
sha3 = "0.10.0"
ripemd = "0.1.0"
blake2 = "0.10.0"
generic-array = "0.14.5"
hex = "0.4.3"
rand = "0.8.4"
tari_crypto = "0.11.2"
parity-scale-codec = {version = "2.3.1", features = ["derive", "chain-error"]}
parity-scale-codec-derive = "2.3.1"
