[package]
name = "crypto"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors = ["Samer Afach <samer.afach@mintlayer.org>", "Ben Marsh <benjamin.marsh@mintlayer.org>", "Enrico Rubboli <enrico.rubboli@mintlayer.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialization = { path = "../serialization" }

secp256k1 = { version = "0.27", default-features = false, features = ["global-context", "rand-std"] }
hmac = "0.12"
bip39 = { version = "2.0", default-features = false, features = ["std", "zeroize"] }
sha-1 = "0.10"
sha2 = "0.10"
sha3 = "0.10"
ripemd = "0.1"
blake2 = "0.10"
rand = "0.8"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
chacha20poly1305 = "0.10"
schnorrkel = "0.10"
merlin = { version = "3.0", default-features = false }
argon2 = { version = "0.5", features = ["std"] }

generic-array.workspace = true
parity-scale-codec.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
test-utils = { path = "../test-utils" }

rstest.workspace = true
hex.workspace = true
rand_chacha = "0.3"
