[package]
name = "crypto"
version = "0.1.0"
edition = "2018"
authors = ["Samer Afach <samer.afach@mintlayer.org>", "Ben Marsh <benjamin.marsh@mintlayer.org>", "Enrico Rubboli <enrico.rubboli@mintlayer.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashing = {version = "0.1.0", git = "https://github.com/mintlayer/hashing.git", branch = "master"}
digest = "0.9.0"
generic-array = "0.14.4"
