[package]
name = "storage-lmdb"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
storage-core = { path = '../core' }
utils = { path = '../../utils' }

lmdb-mintlayer = { git = 'https://github.com/mintlayer/lmdb-rs-mintlayer.git', tag = 'v0.15.0' }

[dev-dependencies]
storage-backend-test-suite = { path = "../backend-test-suite" }

rand = "0.8"

[[test]]
name = "backend"
harness = false
