[package]
name = "storage-lmdb"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"

[dependencies]
logging = { path = '../../logging' }
storage-core = { path = '../core' }
utils = { path = '../../utils' }

lmdb-mintlayer = { git = 'https://github.com/mintlayer/lmdb-rs-mintlayer.git', tag = 'v0.16.2' }

[dev-dependencies]
storage-backend-test-suite = { path = "../backend-test-suite" }
test-utils = { path = "../../test-utils" }
tempdir = "0.3"
rstest = "0.16"

[[test]]
name = "backend"
harness = false
