[package]
name = "storage-lmdb"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
logging = { path = '../../logging' }
storage-core = { path = '../core' }
utils = { path = '../../utils' }

lmdb-mintlayer = { git = 'https://github.com/mintlayer/lmdb-rs-mintlayer.git', tag = 'v0.15.2' }

[dev-dependencies]
storage-backend-test-suite = { path = "../backend-test-suite" }
test-utils = { path = "../../test-utils" }

[[test]]
name = "backend"
harness = false
