[package]
name = "chainstate-storage"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chainstate-types = { path = '../types' }
common = { path = '../../common' }
pos_accounting = {path = '../../pos_accounting'}
serialization = { path = "../../serialization" }
storage = { path = '../../storage', features = ['inmemory'] }
utxo = { path = '../../utxo' }

mockall = { version = "0.11", optional = true }

[dev-dependencies]
crypto = { path = '../../crypto' }
test-utils = {path = '../../test-utils'}
utils = { path = '../../utils' }

itertools.workspace = true
mockall = "0.11"
num-traits = "0.2"
rstest = "0.17"

[features]
mock = [ 'mockall' ]
