on:
  pull_request:
    branches:
      - master
      - staging

name: Clippy check
jobs:
  clippy_check_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --workspace --all-targets -- -D warnings
