on:
  push:
    branches:
      - "**" # target all branches
  pull_request:
    branches:
      - master

name: Static code checks
jobs:
  clippy_check_ubuntu:
    name: Static code checks
    runs-on: ubuntu-latest
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          concurrent_skipping: "same_content_newer"
          skip_after_successful_duplicate: "true"
      - name: Install dependencies
        run: sudo apt-get install -yqq --no-install-recommends build-essential libgtk-3-dev python3 python3-toml
      - uses: actions/checkout@v1

      - name: Install rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Install rust clippy
        run: rustup component add clippy
      - name: Install cargo-deny
        run: cargo install cargo-deny
      - name: Run checks
        run: ./do_checks.sh
