name: Permutation testing

on:
  push:
    branches:
      - "**" # target all branches
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --cfg=loom
  RUST_LOG: debug
  RUST_BACKTRACE: full

jobs:
  test_loom:
    runs-on: ubuntu-latest
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          concurrent_skipping: "same_content_newer"
          skip_after_successful_duplicate: "true"
      - uses: actions/checkout@v2
      - name: Install rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run permutation tests
        run: cargo test --tests --release -p storage -p chainstate-storage -p storage-lmdb -p storage-inmemory
