workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: "$CI_COMMIT_BRANCH"
    - if: "$CI_COMMIT_TAG" 

stages:  
  - fmt        # List of stages for jobs, and their order of execution
  - build
  - test
  - sgh
  - fn

fmt-job:
  stage: fmt
  script:
    cargo fmt --all -- --check

build-job:
  stage: build
  script:
    cargo build --release --locked

test-job:
  stage: test
  script:
    cargo test --release --workspace

sighash-job:
  stage: sgh
  script:
    cargo test --release -p common mixed_sighash_types -- --ignored

fntest-job:
  stage: fn
  script:
    cargo test --release -p mintlayer-test --test functional -- --ignored
