[package]
name = "wallet-cli-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
consensus = { path = "../../consensus" }
logging = { path = "../../logging" }
node-comm = { path = "../wallet-node-client" }
serialization = { path = "../../serialization" }
utils = { path = "../../utils" }
wallet = { path = ".." }
wallet-controller = { path = "../wallet-controller" }
wallet-storage = { path = "../storage" }

clap = { version = "4", features = ["derive"] }
crossterm = "0.26"
directories = "5.0"
reedline = { version = "0.19", features = ["external_printer"] }
shlex = "1.0"
thiserror.workspace = true
tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "sync"] }

[dev-dependencies]
chainstate = { path = "../../chainstate/" }
chainstate-storage = { path = "../../chainstate/storage" }
mempool = { path = "../../mempool" }
node-lib = { path = "../../node-lib" }
p2p = { path = "../../p2p" }
rpc = { path = "../../rpc" }
subsystem = { path = "../../subsystem" }
test-utils = { path = "../../test-utils" }
